### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by platy11** [shannonmoeller/ygor#2]
You say in the README this is MIT licensed, but there is no actual license.

**Comment by shannonmoeller** [comment]
There's a link to the MIT license file in the README which I've considered good enough thus far. Wouldn't hurt to include it in the repo. I haven't been in that habit because updating dozens of copyright year notices on Jan 1 is cumbersome.

**Comment by platy11** [comment]
@shannonmoeller totally understand. I made this issue because [GitHub now shows the repo's license](https://github.com/blog/2252-license-now-displayed-on-repository-overview) and it isn't appearing here.

**Comment by shannonmoeller** [comment]
Done.
